version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/api"
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    restart: always
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6389:6379"
    restart: always

  db:
    image: postgres:16
    container_name: db
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  sidekiq:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - db
    volumes:
      - ./api:/api
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: "postgres://postgres:password@db:5432/api"
    restart: always

volumes:
  postgres_data:
