FROM ruby:3.3.0

ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  yarn \
  netcat-traditional

WORKDIR /api

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . /api

EXPOSE 3000


COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["sh", "/usr/bin/entrypoint.sh"]
